/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miguel
 */
public class UIDim extends javax.swing.JFrame {

    /**
     * Creates new form UIDim
     */
    public UIDim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt11 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        txt41 = new javax.swing.JTextField();
        txt51 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt32 = new javax.swing.JTextField();
        txt42 = new javax.swing.JTextField();
        txt52 = new javax.swing.JTextField();
        txt33 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt43 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt53 = new javax.swing.JTextField();
        lbl11 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lblMedio = new javax.swing.JLabel();
        lblBajo = new javax.swing.JLabel();
        lblAlto = new javax.swing.JLabel();
        lblInterfaces = new javax.swing.JLabel();
        lblArchivos = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        lblSalidas = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        txt14 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt34 = new javax.swing.JTextField();
        txt44 = new javax.swing.JTextField();
        txt54 = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblDimension = new javax.swing.JLabel();
        txtResulTotal = new javax.swing.JTextField();
        lblResulPunFun = new javax.swing.JLabel();
        btnDimAjustado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt11);
        txt11.setBounds(96, 91, 30, 30);
        getContentPane().add(txt21);
        txt21.setBounds(96, 132, 30, 30);
        getContentPane().add(txt31);
        txt31.setBounds(96, 173, 30, 30);
        getContentPane().add(txt41);
        txt41.setBounds(96, 214, 30, 30);
        getContentPane().add(txt51);
        txt51.setBounds(96, 255, 30, 30);
        getContentPane().add(txt12);
        txt12.setBounds(168, 91, 30, 30);
        getContentPane().add(txt22);
        txt22.setBounds(168, 132, 30, 30);
        getContentPane().add(txt32);
        txt32.setBounds(168, 173, 30, 30);
        getContentPane().add(txt42);
        txt42.setBounds(168, 214, 30, 30);
        getContentPane().add(txt52);
        txt52.setBounds(168, 255, 30, 30);
        getContentPane().add(txt33);
        txt33.setBounds(241, 173, 30, 30);
        getContentPane().add(txt13);
        txt13.setBounds(241, 91, 30, 30);
        getContentPane().add(txt43);
        txt43.setBounds(241, 214, 30, 30);
        getContentPane().add(txt23);
        txt23.setBounds(241, 132, 30, 30);
        getContentPane().add(txt53);
        txt53.setBounds(241, 255, 30, 30);

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl11.setText("x3");
        getContentPane().add(lbl11);
        lbl11.setBounds(130, 95, 20, 20);

        lbl31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl31.setText("x3");
        getContentPane().add(lbl31);
        lbl31.setBounds(130, 177, 20, 20);

        lbl21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl21.setText("x4");
        getContentPane().add(lbl21);
        lbl21.setBounds(130, 136, 20, 20);

        lbl41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl41.setText("x7");
        getContentPane().add(lbl41);
        lbl41.setBounds(130, 218, 20, 20);

        lbl51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl51.setText("x5");
        getContentPane().add(lbl51);
        lbl51.setBounds(130, 259, 20, 20);

        lbl42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl42.setText("x10");
        getContentPane().add(lbl42);
        lbl42.setBounds(202, 218, 21, 20);

        lbl52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl52.setText("x7");
        getContentPane().add(lbl52);
        lbl52.setBounds(202, 259, 20, 20);

        lbl32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl32.setText("x4");
        getContentPane().add(lbl32);
        lbl32.setBounds(202, 177, 20, 20);

        lbl22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl22.setText("x5");
        getContentPane().add(lbl22);
        lbl22.setBounds(202, 136, 20, 20);

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl12.setText("x4");
        getContentPane().add(lbl12);
        lbl12.setBounds(202, 95, 20, 20);

        lbl33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl33.setText("x6");
        getContentPane().add(lbl33);
        lbl33.setBounds(275, 177, 20, 20);

        lbl23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl23.setText("x7");
        lbl23.setToolTipText("");
        getContentPane().add(lbl23);
        lbl23.setBounds(275, 136, 20, 20);

        lbl53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl53.setText("x10");
        getContentPane().add(lbl53);
        lbl53.setBounds(275, 259, 21, 20);

        lbl43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl43.setText("x15");
        getContentPane().add(lbl43);
        lbl43.setBounds(275, 218, 21, 20);

        lbl13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl13.setText("x6");
        getContentPane().add(lbl13);
        lbl13.setBounds(275, 95, 20, 20);

        lblMedio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedio.setForeground(new java.awt.Color(0, 0, 255));
        lblMedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedio.setText("Medio");
        getContentPane().add(lblMedio);
        lblMedio.setBounds(168, 69, 54, 16);

        lblBajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBajo.setForeground(new java.awt.Color(0, 0, 255));
        lblBajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBajo.setText("Bajo");
        getContentPane().add(lblBajo);
        lblBajo.setBounds(96, 69, 54, 16);

        lblAlto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlto.setForeground(new java.awt.Color(0, 0, 255));
        lblAlto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlto.setText("Alto");
        getContentPane().add(lblAlto);
        lblAlto.setBounds(241, 69, 54, 16);

        lblInterfaces.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInterfaces.setForeground(new java.awt.Color(0, 102, 0));
        lblInterfaces.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterfaces.setText("Interfaces");
        getContentPane().add(lblInterfaces);
        lblInterfaces.setBounds(10, 261, 80, 16);

        lblArchivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArchivos.setForeground(new java.awt.Color(0, 102, 0));
        lblArchivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArchivos.setText("Archivos");
        getContentPane().add(lblArchivos);
        lblArchivos.setBounds(10, 220, 80, 16);

        lblConsultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsultas.setForeground(new java.awt.Color(0, 102, 0));
        lblConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultas.setText("Consultas");
        getContentPane().add(lblConsultas);
        lblConsultas.setBounds(10, 179, 80, 16);

        lblSalidas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSalidas.setForeground(new java.awt.Color(0, 102, 0));
        lblSalidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalidas.setText("Salidas");
        getContentPane().add(lblSalidas);
        lblSalidas.setBounds(10, 138, 80, 16);

        lblEntradas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(0, 102, 0));
        lblEntradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntradas.setText("Entradas");
        getContentPane().add(lblEntradas);
        lblEntradas.setBounds(10, 97, 80, 16);

        txt14.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txt14);
        txt14.setBounds(325, 91, 30, 30);

        txt24.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txt24);
        txt24.setBounds(325, 132, 30, 30);

        txt34.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txt34);
        txt34.setBounds(325, 173, 30, 30);

        txt44.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txt44);
        txt44.setBounds(325, 214, 30, 30);

        txt54.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txt54);
        txt54.setBounds(325, 255, 30, 30);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(314, 69, 54, 16);

        lblDimension.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDimension.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDimension.setText("DIMENSIONAMIENTO");
        getContentPane().add(lblDimension);
        lblDimension.setBounds(70, 20, 251, 32);

        txtResulTotal.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtResulTotal);
        txtResulTotal.setBounds(300, 296, 80, 30);

        lblResulPunFun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResulPunFun.setForeground(new java.awt.Color(255, 0, 0));
        lblResulPunFun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResulPunFun.setText("Puntos de Función");
        getContentPane().add(lblResulPunFun);
        lblResulPunFun.setBounds(189, 302, 101, 16);

        btnDimAjustado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDimAjustado.setText("Dimensionamiento Ajustado");
        getContentPane().add(btnDimAjustado);
        btnDimAjustado.setBounds(190, 340, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDimAjustado;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lblAlto;
    private javax.swing.JLabel lblArchivos;
    private javax.swing.JLabel lblBajo;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblDimension;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblInterfaces;
    private javax.swing.JLabel lblMedio;
    private javax.swing.JLabel lblResulPunFun;
    private javax.swing.JLabel lblSalidas;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt32;
    private javax.swing.JTextField txt33;
    private javax.swing.JTextField txt34;
    private javax.swing.JTextField txt41;
    private javax.swing.JTextField txt42;
    private javax.swing.JTextField txt43;
    private javax.swing.JTextField txt44;
    private javax.swing.JTextField txt51;
    private javax.swing.JTextField txt52;
    private javax.swing.JTextField txt53;
    private javax.swing.JTextField txt54;
    private javax.swing.JTextField txtResulTotal;
    // End of variables declaration//GEN-END:variables
}
