/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miguel
 */
public class UIDimAjus extends javax.swing.JFrame {

    /**
     * Creates new form UIDimAjus
     */
    public UIDimAjus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        lblConExp = new javax.swing.JLabel();
        lblTasTra = new javax.swing.JLabel();
        lblEntDat = new javax.swing.JLabel();
        lblEfiUsu = new javax.swing.JLabel();
        lblProDis = new javax.swing.JLabel();
        lblObjRen = new javax.swing.JLabel();
        lblComDat = new javax.swing.JLabel();
        lblActLin = new javax.swing.JLabel();
        lblProInt = new javax.swing.JLabel();
        lblConIns = new javax.swing.JLabel();
        lblReuCod = new javax.swing.JLabel();
        lblFacOpe = new javax.swing.JLabel();
        lblInsMul = new javax.swing.JLabel();
        lblFacCam = new javax.swing.JLabel();
        lblDimensionAjust = new javax.swing.JLabel();
        txtTot1 = new javax.swing.JTextField();
        lblTot1 = new javax.swing.JLabel();
        lblTot2 = new javax.swing.JLabel();
        txtTot2 = new javax.swing.JTextField();
        txtACT = new javax.swing.JTextField();
        lblACT = new javax.swing.JLabel();
        txtACTA = new javax.swing.JTextField();
        lblACTA = new javax.swing.JLabel();
        lblPFA = new javax.swing.JLabel();
        txtPFA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConExp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConExp.setForeground(new java.awt.Color(51, 51, 51));
        lblConExp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConExp.setText("Configuración de Explotación Compartida");

        lblTasTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTasTra.setForeground(new java.awt.Color(51, 0, 102));
        lblTasTra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTasTra.setText("Tasas de Transacciones");

        lblEntDat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEntDat.setForeground(new java.awt.Color(51, 51, 51));
        lblEntDat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntDat.setText("Entrada de Datos en Línea");

        lblEfiUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEfiUsu.setForeground(new java.awt.Color(51, 0, 102));
        lblEfiUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEfiUsu.setText("Eficiencia con el Usuario Final");

        lblProDis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProDis.setForeground(new java.awt.Color(51, 51, 51));
        lblProDis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProDis.setText("Proceso Distribuido");

        lblObjRen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblObjRen.setForeground(new java.awt.Color(51, 0, 102));
        lblObjRen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObjRen.setText("Objetivos de Rendimiento");

        lblComDat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComDat.setForeground(new java.awt.Color(51, 0, 102));
        lblComDat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComDat.setText("Comunicación de Datos");

        lblActLin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActLin.setForeground(new java.awt.Color(51, 51, 51));
        lblActLin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblActLin.setText("Actualizaciones en Línea");

        lblProInt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProInt.setForeground(new java.awt.Color(51, 0, 102));
        lblProInt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProInt.setText("Lógica de Proceso Interno Compleja");

        lblConIns.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConIns.setForeground(new java.awt.Color(51, 0, 102));
        lblConIns.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConIns.setText("Conversión de Instalación Contempladas");

        lblReuCod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReuCod.setForeground(new java.awt.Color(51, 51, 51));
        lblReuCod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReuCod.setText("Reusabilidad de Código");

        lblFacOpe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFacOpe.setForeground(new java.awt.Color(51, 51, 51));
        lblFacOpe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFacOpe.setText("Facilidad de Operación");

        lblInsMul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInsMul.setForeground(new java.awt.Color(51, 0, 102));
        lblInsMul.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInsMul.setText("Instalaciones Múltiples");

        lblFacCam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFacCam.setForeground(new java.awt.Color(51, 51, 51));
        lblFacCam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFacCam.setText("Facilidad de Cambios");

        lblDimensionAjust.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDimensionAjust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDimensionAjust.setText("DIMENSIONAMIENTO AJUSTADO");

        txtTot1.setForeground(new java.awt.Color(255, 0, 0));

        lblTot1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTot1.setForeground(new java.awt.Color(255, 0, 0));
        lblTot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTot1.setText("Total 1");

        lblTot2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTot2.setForeground(new java.awt.Color(255, 0, 0));
        lblTot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTot2.setText("Total 2");
        lblTot2.setToolTipText("");

        txtTot2.setForeground(new java.awt.Color(255, 0, 0));

        txtACT.setForeground(new java.awt.Color(0, 0, 255));

        lblACT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblACT.setForeground(new java.awt.Color(0, 0, 204));
        lblACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACT.setText("Ajuste de Complejidad Tecnica (ACT)");

        txtACTA.setForeground(new java.awt.Color(0, 0, 255));

        lblACTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblACTA.setForeground(new java.awt.Color(0, 0, 204));
        lblACTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTA.setText("Complejidad del Proceso Ajustada (ACTA)");

        lblPFA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPFA.setForeground(new java.awt.Color(0, 0, 204));
        lblPFA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPFA.setText("Total de Puntos de Fucion Ajustados (PFA)");

        txtPFA.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPFA)
                        .addGap(10, 10, 10)
                        .addComponent(txtPFA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblACTA)
                                .addGap(10, 10, 10)
                                .addComponent(txtACTA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblACT)
                                .addGap(10, 10, 10)
                                .addComponent(txtACT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblTot1)
                        .addGap(10, 10, 10)
                        .addComponent(txtTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTot2)
                        .addGap(10, 10, 10)
                        .addComponent(txtTot2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDimensionAjust)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblConExp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTasTra, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblEntDat, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEfiUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblProDis, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblObjRen, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblComDat, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblActLin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblProInt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblConIns, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblReuCod, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFacOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInsMul, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFacCam, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDimensionAjust)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblActLin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReuCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConIns))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFacOpe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInsMul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFacCam)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComDat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProDis)
                            .addComponent(lblProInt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObjRen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConExp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTasTra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntDat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfiUsu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTot1)
                            .addComponent(lblTot2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtACT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblACT)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtACTA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblACTA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPFA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPFA)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDimAjus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDimAjus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDimAjus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDimAjus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDimAjus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblACT;
    private javax.swing.JLabel lblACTA;
    private javax.swing.JLabel lblActLin;
    private javax.swing.JLabel lblComDat;
    private javax.swing.JLabel lblConExp;
    private javax.swing.JLabel lblConIns;
    private javax.swing.JLabel lblDimensionAjust;
    private javax.swing.JLabel lblEfiUsu;
    private javax.swing.JLabel lblEntDat;
    private javax.swing.JLabel lblFacCam;
    private javax.swing.JLabel lblFacOpe;
    private javax.swing.JLabel lblInsMul;
    private javax.swing.JLabel lblObjRen;
    private javax.swing.JLabel lblPFA;
    private javax.swing.JLabel lblProDis;
    private javax.swing.JLabel lblProInt;
    private javax.swing.JLabel lblReuCod;
    private javax.swing.JLabel lblTasTra;
    private javax.swing.JLabel lblTot1;
    private javax.swing.JLabel lblTot2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextField txtACT;
    private javax.swing.JTextField txtACTA;
    private javax.swing.JTextField txtPFA;
    private javax.swing.JTextField txtTot1;
    private javax.swing.JTextField txtTot2;
    // End of variables declaration//GEN-END:variables
}
