package medidor.vista;

import medidor.controlador.IMain;

public class UIMain extends javax.swing.JFrame {
    
    private IMain interfaceMain;

    public UIMain(IMain interfaceMain) {
        this.setVisible(true);
        initComponents();
        this.interfaceMain = interfaceMain;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalidad = new javax.swing.JButton();
        btnRiesgos = new javax.swing.JButton();
        btnDimens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalidad.setText("Medidor de Calidad");
        btnCalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalidadActionPerformed(evt);
            }
        });

        btnRiesgos.setText("Gestión de Riesgos");
        btnRiesgos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiesgosActionPerformed(evt);
            }
        });

        btnDimens.setText("Dimensionamiento");
        btnDimens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDimensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDimens)
                    .addComponent(btnRiesgos)
                    .addComponent(btnCalidad))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnCalidad)
                .addGap(26, 26, 26)
                .addComponent(btnRiesgos)
                .addGap(27, 27, 27)
                .addComponent(btnDimens)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRiesgosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiesgosActionPerformed
        interfaceMain.mostrarRiesgos();
    }//GEN-LAST:event_btnRiesgosActionPerformed

    private void btnCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalidadActionPerformed
        interfaceMain.mostrarMedidorCalidad();
    }//GEN-LAST:event_btnCalidadActionPerformed

    private void btnDimensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDimensActionPerformed
        interfaceMain.mostrarDimensionamiento();
    }//GEN-LAST:event_btnDimensActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalidad;
    private javax.swing.JButton btnDimens;
    private javax.swing.JButton btnRiesgos;
    // End of variables declaration//GEN-END:variables
}
